# Generated by Django 6.0.6 on 2026-09-05 09:35

from django.db import migrations, models


def fix_other_gender(apps, schema_editor):
    Patient = apps.get_model("api", "Patient")
    # Update any existing 'O' patients to a valid gender
    Patient.objects.filter(gender="O").update(gender="M")


def unfix_other_gender(apps, schema_editor):
    # No-op reverse
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_conversationsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.RunPython(fix_other_gender, unfix_other_gender),
    ]
